# Generated by Django 4.1.4 on 2022-12-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compagnie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnie',
            name='logo',
            field=models.ImageField(upload_to='compagnie'),
        ),
    ]
